/**
 * This Java source file was initially generated by the Gradle 'init' task.
 * Created by Ronald on 14-9-2020.
 *
 */
package calculatorPackage;

public class App {
	
	public String getGreeting() {
        return "Hello world.";
    }
    public static void main(String argv[]) {
        Calculations cocker = new Calculations(); // according to https://en.wikipedia.org/wiki/Cocker%27s_Arithmetick
        System.out.println(cocker.product(4, 7));
        System.out.println(cocker.sum(12, 33));
        System.out.println(cocker.square(23));
    }
}