/*
 * This Java source file was initially generated by the Gradle 'init' task.
 */
package calculatorPackage;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
	Calculations calculator = new Calculations();
    int a=10; // attribute of the calculations
    int b=14; // attribute of the calculations
	
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test public void testProduct() {
        int result = calculator.product(a, b);
        assertTrue(result == 140);
        a=25;
    }

    @Test public void testSum() {
        int result = calculator.sum(a, b);
        assertTrue(result == 24);
    }

    @Test public void testSquare() {
        int result = calculator.square(a);
        assertTrue(result == 100);
    }
	
    @Test public void testSquareWrong() {
        int result = calculator.square(b);
        assertTrue(result == 100);
    }
}
